apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: mmumshad/simple-webapp-color
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP
      env:
        - name: APP_COLOR
          value: "red"