apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume
spec:
  containers:
    - name: bdd
      image: mysql
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: eazytraining
        - name: MYSQL_USER
          value: eazy
        - name: MYSQL_PASSWORD
          value: eazy
  volumes:
    - name: mysql-data
      hostPath:
        path: /mnt/c/Users/testiez/Documents/kubernetes_projects/tp4/data
        type: Directory